// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/proto/field.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Farm  int64 `protobuf:"varint,1,opt,name=farm,proto3" json:"farm,omitempty"`
	Zone  int64 `protobuf:"varint,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Field int64 `protobuf:"varint,3,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *FieldRequest) Reset() {
	*x = FieldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRequest) ProtoMessage() {}

func (x *FieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRequest.ProtoReflect.Descriptor instead.
func (*FieldRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_field_proto_rawDescGZIP(), []int{0}
}

func (x *FieldRequest) GetFarm() int64 {
	if x != nil {
		return x.Farm
	}
	return 0
}

func (x *FieldRequest) GetZone() int64 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *FieldRequest) GetField() int64 {
	if x != nil {
		return x.Field
	}
	return 0
}

type FieldCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FieldCode) Reset() {
	*x = FieldCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldCode) ProtoMessage() {}

func (x *FieldCode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldCode.ProtoReflect.Descriptor instead.
func (*FieldCode) Descriptor() ([]byte, []int) {
	return file_api_proto_field_proto_rawDescGZIP(), []int{1}
}

func (x *FieldCode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FieldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int64         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FieldRequest *FieldRequest `protobuf:"bytes,2,opt,name=fieldRequest,proto3" json:"fieldRequest,omitempty"`
}

func (x *FieldResponse) Reset() {
	*x = FieldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_field_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldResponse) ProtoMessage() {}

func (x *FieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_field_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldResponse.ProtoReflect.Descriptor instead.
func (*FieldResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_field_proto_rawDescGZIP(), []int{2}
}

func (x *FieldResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FieldResponse) GetFieldRequest() *FieldRequest {
	if x != nil {
		return x.FieldRequest
	}
	return nil
}

var File_api_proto_field_proto protoreflect.FileDescriptor

var file_api_proto_field_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x22,
	0x4c, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66,
	0x61, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x1b, 0x0a,
	0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x0d, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x7a, 0x0a,
	0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_field_proto_rawDescOnce sync.Once
	file_api_proto_field_proto_rawDescData = file_api_proto_field_proto_rawDesc
)

func file_api_proto_field_proto_rawDescGZIP() []byte {
	file_api_proto_field_proto_rawDescOnce.Do(func() {
		file_api_proto_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_field_proto_rawDescData)
	})
	return file_api_proto_field_proto_rawDescData
}

var file_api_proto_field_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_field_proto_goTypes = []interface{}{
	(*FieldRequest)(nil),  // 0: api.pb.FieldRequest
	(*FieldCode)(nil),     // 1: api.pb.FieldCode
	(*FieldResponse)(nil), // 2: api.pb.FieldResponse
}
var file_api_proto_field_proto_depIdxs = []int32{
	0, // 0: api.pb.FieldResponse.fieldRequest:type_name -> api.pb.FieldRequest
	0, // 1: api.pb.FieldService.Create:input_type -> api.pb.FieldRequest
	1, // 2: api.pb.FieldService.Get:input_type -> api.pb.FieldCode
	2, // 3: api.pb.FieldService.Create:output_type -> api.pb.FieldResponse
	2, // 4: api.pb.FieldService.Get:output_type -> api.pb.FieldResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_field_proto_init() }
func file_api_proto_field_proto_init() {
	if File_api_proto_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_field_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_field_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_field_proto_goTypes,
		DependencyIndexes: file_api_proto_field_proto_depIdxs,
		MessageInfos:      file_api_proto_field_proto_msgTypes,
	}.Build()
	File_api_proto_field_proto = out.File
	file_api_proto_field_proto_rawDesc = nil
	file_api_proto_field_proto_goTypes = nil
	file_api_proto_field_proto_depIdxs = nil
}
